[package]
name = "p3-miden-dev-utils"
description = "Shared development utilities (benchmarks, test fixtures) for p3-miden crates"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
homepage.workspace = true

[dependencies]
# Internal
p3-miden-stateful-hasher.workspace = true

# Plonky3
p3-challenger.workspace = true
p3-field.workspace = true
p3-goldilocks.workspace = true
p3-keccak.workspace = true
p3-matrix.workspace = true
p3-symmetric.workspace = true

# Third-party
rand.workspace = true

[features]
parallel = []
